site_name: Robot Framework
site_description: Robot Framework is a generic open source automation framework. This reference manual covers all its features in detail.
site_url: https://pekkaklarck.github.io/manual/    # The mike plugin requires the trailing slash.
repo_url: https://github.com/robotframework/robotframework
edit_uri: https://github.com/pekkaklarck/manual/blob/main/doc/manual/docs
copyright: |
  &copy; 2026- <a href="https://robotframework.org/foundation" target="_blank" rel="noopener">Robot Framework Foundation</a>
docs_dir: doc/manual/docs
watch:
  - INSTALL.md
  - src/robot/
  - doc/manual/overrides

nav:
  - Manual: index.md
  - Install:
      - install/index.md
  - Data:
      - data/index.md
      - Syntax: data/syntax.md
      - Creating tests: data/tests.md
      - Creating tasks: data/tasks.md
      - Creating suites: data/suites.md
      - Using libraries: data/libraries.md
      - Variables: data/variables.md
      - User keywords: data/user-keywords.md
      - Resource files: data/resource-files.md
      - Variable files: data/variable-files.md
      - Control structures: data/control.md
      - Advanced features: data/advanced.md
  - Execution:
      - execution/index.md
      - Basic usage: execution/basics.md
      - Test execution: execution/tests.md
      - Task execution: execution/tasks.md
      - Configuring execution: execution/configuration.md
      - Results: execution/results.md
  - Libraries:
      - libraries/index.md
  - Tools:
      - tools/index.md
      - Rebot: tools/rebot.md
      - Libdoc: tools/libdoc.md
      - Testdoc: tools/testdoc.md
  - Extend:
      - extend/index.md
      - Library interface: extend/libraries.md
      - Dynamic library interface: extend/dynamic.md
      - Remote library interface: extend/remote.md
      - Listener interface: extend/listeners.md
      - Parser interface: extend/parsing.md
      - Execution and result models: extend/models.md
      - JSON models: extend/json.md
      - XML output: extend/xml.md
  - API: api/    # API navigation is generated by docs/api/generate.py
  - Appendix:
      - appendix/index.md
      - appendix/settings.md
      - appendix/cli.md
      - appendix/translations.md
      - appendix/expressions.md
      - appendix/doc-format.md
      - appendix/time-format.md
      - appendix/registrations.md
  - Glossary: glossary.md

extra_css:
  - assets/extra.css

theme:
  name: material
  logo: assets/logo-white.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  custom_dir: doc/manual/overrides
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.integrate
  language: en
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - social:
      cards_layout_options:
        background_color: "#00c0b5"
  - autorefs
  - exclude:
      glob:
        - api/generate.py
        - install/generate.py
        - libraries/generate.py
  - gen-files:
      scripts:
        - doc/manual/docs/api/generate.py
        - doc/manual/docs/install/generate.py
        - doc/manual/docs/libraries/generate.py
  - literate-nav:
      nav_file: nav.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          inventories:
            - https://docs.python.org/3/objects.inv
          options:
            inherited_members: true
            members_order: source
            group_by_category: false
            show_root_heading: true
            merge_init_into_class: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_signature_annotations: true
            signature_crossrefs: true
            separate_signature: true
  - mike:
      canonical_version: latest
  - ezglossary:
      use_default: true
      ignore_case: true
      plurals: en
      tooltip: full
      inline_refs: list

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/robotframework/
    - icon: fontawesome/brands/slack
      link: https://slack.robotframework.org
    - icon: fontawesome/brands/discourse
      link: https://forum.robotframework.org
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/robot-framework-foundation
  version:
    provider: mike
    alias: true

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: true
      toc_depth: 3
  # PyMdown Extensions we use (there are more)
  # https://facelessuser.github.io/pymdown-extensions/
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      default_lang: python
      linenums: true
      anchor_linenums: true
      line_anchors: example
      line_spans: line
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      user: robotframework
      repo: robotframework
  - pymdownx.saneheaders
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
